### ISSUE TITLE
Vivaldi support

### ISSUE THREAD

**Issue by Donkeyfish87** [mdreizin/chrome-bookmarks-alfred-workflow#28]
It would be great with support for Vivaldi. I think it should be easy to implement, since the folder seems to be identical to Chrome. I.e ~/Library/Application Support/Vivaldi/Default/bookmarks.

I tried myself, but have never tried Go before so didn't get it to work.

**Comment by mdreizin** [comment]
@Donkeyfish87 It is easy to do:

1. Fork the repo
2. Edit `browser.yml` and append the following lines:

```yml
- id: "bac1400d-5487-42a9-8571-95131e4dd98b"
  name: "vivaldi"
  fullName: "com.vivaldi.Vivaldi"
  description: "Vivaldi"
  path: "~/Library/Application Support/Vivaldi"
  iconUrl: "img/vivaldi.png"
  profileName: "Default"
```

3. Add `workflow/img/vivaldi.png`

4. Run `make workflow`, open `build/` folder and find `chrome-bookmarks.alfredworkflow` here.
