### ISSUE TITLE
add support for ungoogled chromium

### ISSUE THREAD

**Issue by nikitavoloboev** [mdreizin/chrome-bookmarks-alfred-workflow#30]
I installed [this](https://github.com/Eloston/ungoogled-chromium). However the chromium bookmark searcher does not seem to work with it. It just gives an error : 

![2017-08-25 at 02 39](https://user-images.githubusercontent.com/6391776/29694717-94ffdbc0-893e-11e7-919d-28b86c4c30f3.png)

If you can add support for it, it would be amazing. Thank you.

**Comment by mdreizin** [comment]
@nikitavoloboev Please try to use `chrome-profiles` command and select your profile.

**Comment by mdreizin** [comment]
@nikitavoloboev It looks like that you didn't do that.

Please see https://github.com/mdreizin/chrome-bookmarks-alfred-workflow#options

Also you could do that manually:

- Open Alfred
- Go to Workflows
- Select `Chrome Bookmarks`
- Select `Open in Finder` from menu
- Open `browser.yml`
- Find `name: "chromium"` configuration and add `profileName: "Default"` to it

```yml
- id: "5c5a3de8-474a-42bf-99f6-c61f793a6625"
  name: "chromium"
  fullName: "org.chromium.Chromium"
  description: "Chromium"
  path: "~/Library/Application Support/Chromium"
  iconUrl: "img/chromium.png"
  profileName: "Default"
```
